global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  websecure:
    address: :443

log:
  filePath: /var/log/traefik.log

accessLog:
  filePath: /var/log/access.log

api:
  insecure: false
  dashboard: false

ping:
  entryPoint: traefik

certificatesResolvers:
  default:
    acme:
      email: "${acme_account_email}"
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

providers:
  kubernetesIngress:
    # The private endpoint for the cluster created is expected to stay
    # the same as the second IP in 172.16.0.0/28 assigned to the cluster.
    endpoint: "https://172.16.0.2:443"
    token: "${traefik_service_token}"
    certAuthFilePath: "/etc/ssl/certs/k8s.crt"
    ingressClass: traefik
    namespaces: ["ingress"]